meta_product_name: "ST&ND"
meta_title: "ST&ND - Smart Team Collaboration That Works (from start to end)"
meta_description: "ST&ND is the digital operating system for teams.
It’s a real-time platform to prioritise, track and balance your core processes."
meta_image: "social-media.png" # should exist in `app/assets/images/`
